### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by RomanTruba** [badoo/ios-collection-batch-updates#3]
If you turn on `Documentation Comments` warning, you will see messages like:
```
BMACollectionUpdates.h:35:37: Not a Doxygen trailing comment
```
Which are caused by commented generics placed right in declaration, like 
```
@property (nonatomic, copy) NSArray /*<id<BMAUpdatableCollectionItem>>*/ *items;
```

Please uncomment, or remove.

Also there are two extra warnings about parameter names:
```
BMACollectionBatchUpdates/UICollectionView+BMABatchUpdates.h:31:12: Parameter 'applyChangesBlock' not found in the function declaration
BMACollectionBatchUpdates/UITableView+BMABatchUpdates.h:31:12: Parameter 'applyChangesBlock' not found in the function declaration
```

**Comment by Viacheslav-Radchenko** [comment]
I've added annotations for nullability and containers types. You shouldn't see these warnings anymore.
