### ISSUE TITLE
Comparing CollectionItems

### ISSUE THREAD

**Issue by damikdk** [badoo/ios-collection-batch-updates#5]
Hello,
For starters, thank you! You did a very good job with this library, it had saved our team a ton of time.

While we're happily using it, we have a question regarding collection of updated items in [this code](https://github.com/badoo/ios-collection-batch-updates/blob/master/BMACollectionBatchUpdates/BMACollectionUpdates.m#L262) - why are you comparing items through `isEqual` method as objects when they already have `uid` property for item by protocol ?
We're using newly created items for each sections update and were forced to implement custom `isEqual` for it to work properly, which, while not complex, could be unnecessary 'cause we already have a `uid` property that is uniquely identifies item in section and can be used for comparisons.

But maybe we just do not understand something ?

**Comment by Viacheslav-Radchenko** [comment]
Hi @damikdk use of isEqual provides more flexibility. 
I will try to explain with example. In most of the cases direct comparison by uid will be enough, but sometimes your model may contain additional properties, for example online status (online or offline). In this case your uid not changing, but state of the model does, and you need to generate collection view update for this cell. isEqual used exactly for this purpose, to identify changes in existing model and generate cell update.

**Comment by damikdk** [comment]
Thanks for a quick reply!
Ok, I understand the reasoning a bit better now.
Could you please add some note about the need to implement custom `isEqual` when using new items with `uid`s identical identical to old ones to update collection in the **How To Use** readme section ?
At least for our team it could have made things easier in the past, and I'm sure we're not the only ones.

**Comment by Viacheslav-Radchenko** [comment]
I added description about isEqual in readme. 
Alternatively it probably will be better to pass block for items comparison explicitly in calculateUpdatesForOldModel:newModel... and remove this implicit dependency on isEqual.

**Comment by damikdk** [comment]
Thank you!
